sll: sll.c
	@gcc -o sll sll.c

stacka: stacka.c
	@gcc -o stacka stacka.c

stackl: stackl.c
	@gcc -o stackl stackl.c

hasht: hash_table.c
	@gcc -o hash_table hash_table.c

clean:
	@rm sll stacka stackl hash_table
	
