sll: singly_linked_list.c
	@gcc -o singly_linked_list singly_linked_list.c

stacka: stack_array_version.c
	@gcc -o stack_array_version stack_array_version.c

clean:
	@rm singly_linked_list stack_array_version
	
